org: yecksin
app: yeckslapp
service: yecksl
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x

functions:
  api:
    handler: dist/handler.handler
    events:
      - httpApi: '*'
plugins:
  - serverless-offline
  - 'serverless-plugin-typescript-express'